#theme: jekyll-theme-cayman
title: HokStack - Stable HELM Chart Repo
description: HokStack Stable HELM Charts
theme: minima
url: "https://charts.hokstack.io/"
repo_name: hokstack

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
