#theme: jekyll-theme-cayman
title: HokStack - Run Hadoop on Kubernetes
description: HokStack Stable HELM Charts
theme: minima
url: "https://charts.hokstack.io/"
repo_name: hok/hokstack

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
